//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELMs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Attachment
    {
        public int id { get; set; }
        public string application_type { get; set; }
        public Nullable<int> application_id { get; set; }
        public Nullable<int> attachment_id { get; set; }
    }
}
