//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELMs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int equipment_id { get; set; }
        public string system_equipment_code { get; set; }
        public string standard_equipment_code { get; set; }
        public string equipment_name { get; set; }
        public Nullable<int> equipment_img { get; set; }
        public string serial_no { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string unit { get; set; }
        public string specification { get; set; }
        public Nullable<int> img { get; set; }
        public string responsibler { get; set; }
        public string usage_status { get; set; }
        public string type_equipment { get; set; }
        public string note { get; set; }
        public string category_code { get; set; }
    }
}
