//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELMs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Request_Application_Detail
    {
        public int application_detail_id { get; set; }
        public string ir_application_code { get; set; }
        public string system_equipment_code { get; set; }
        public string inventory_results { get; set; }
        public Nullable<int> actual_quantity { get; set; }
        public string actual_usage_status { get; set; }
        public Nullable<System.DateTime> inventory_date { get; set; }
    }
}
