//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELMs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Request_Application
    {
        public int application_id { get; set; }
        public string ir_application_code { get; set; }
        public string requester { get; set; }
        public string request_date { get; set; }
        public string performer { get; set; }
        public int total_equipment { get; set; }
        public bool status { get; set; }
    }
}
