//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELMs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Equipment_Allocation_Application = new HashSet<Equipment_Allocation_Application>();
            this.Equipment_Project_History = new HashSet<Equipment_Project_History>();
            this.Member_Project_History = new HashSet<Member_Project_History>();
            this.Equipment_Handover_Form = new HashSet<Equipment_Handover_Form>();
        }
    
        public int project_id { get; set; }
        public string project_name { get; set; }
        public string acronym { get; set; }
        public string description { get; set; }
        public string manager { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string creater { get; set; }
        public bool status { get; set; }
        public Nullable<int> location_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Allocation_Application> Equipment_Allocation_Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Project_History> Equipment_Project_History { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member_Project_History> Member_Project_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Handover_Form> Equipment_Handover_Form { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
