//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELMs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int project_id { get; set; }
        public string project_code { get; set; }
        public string project_name { get; set; }
        public string acronym { get; set; }
        public string description { get; set; }
        public string manager { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string creater { get; set; }
        public bool status { get; set; }
        public Nullable<int> location_id { get; set; }
    }
}
