//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SELMs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SELMsContext : DbContext
    {
        public SELMsContext()
            : base("name=SELMsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Equipment_Allocation_Application> Equipment_Allocation_Application { get; set; }
        public virtual DbSet<Equipment_Allocation_Application_Detail> Equipment_Allocation_Application_Detail { get; set; }
        public virtual DbSet<Equipment_Component> Equipment_Component { get; set; }
        public virtual DbSet<Equipment_Handover_Form> Equipment_Handover_Form { get; set; }
        public virtual DbSet<Equipment_Handover_Form_Detail> Equipment_Handover_Form_Detail { get; set; }
        public virtual DbSet<Equipment_Import_Application> Equipment_Import_Application { get; set; }
        public virtual DbSet<Equipment_Import_Application_Detail> Equipment_Import_Application_Detail { get; set; }
        public virtual DbSet<Equipment_Location_History> Equipment_Location_History { get; set; }
        public virtual DbSet<Equipment_Project_History> Equipment_Project_History { get; set; }
        public virtual DbSet<Equipment_Usage_History> Equipment_Usage_History { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Inventory_Request_Application> Inventory_Request_Application { get; set; }
        public virtual DbSet<Inventory_Request_Application_Detail> Inventory_Request_Application_Detail { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Member_Location_History> Member_Location_History { get; set; }
        public virtual DbSet<Member_Project_History> Member_Project_History { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Project_Investment_Cost_Application> Project_Investment_Cost_Application { get; set; }
        public virtual DbSet<Project_Investment_Cost_Application_Detail> Project_Investment_Cost_Application_Detail { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
