//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_QLBH_BQD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_USERS
    {
        public int ID { get; set; }
        public string CODE_MEMBER { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string FULL_NAME { get; set; }
        public string CODE_POSITION { get; set; }
        public bool IS_ADMIN { get; set; }
    }
}
